/**
 * RockPaperScissorsLizardSpock.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GameResultDto { 
    id: number;
    playerId?: number;
    player?: number;
    computer?: number;
    results?: string;
    playedAt?: Date;
    includeInScore?: boolean;
    playerName?: string;
    playerChoiceName?: string;
    computerChoiceName?: string;
    readonly time?: string;
}